name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: node:16

    services:
      mongodb:
        image: mongodb
        env:
          MONGODB_USER: url_shorteruser
          MONGODB_PASSWORD: somepasswordskuaddb
          MONGODB_DB: url_shorter
        ports:
          - 27111:27111

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - name: Run tests
        run: npm run test:ci
        env:
          PORT: 3000
          NODE_ENV: 'testing'
          DATABASE_URL: 'mongodb://url_shorteruser:somepasswordskuaddb@185.4.178.68:27111/url_shorter'

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: NPM install
        run: npm install
      - name: Build app
        run: npm run build
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: alayesanmifemi@gmail.com
          heroku_app_name: url-shorter-service